spring:
  boot:
    admin:
#      url: http://localhost:8090
      client:
        enabled: false
  application:
    name: ServiceDemo
server:
  port: 8100
logging:
  level:
   root: info
eureka:
  instance:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
