spring:
  boot:
    admin:
      context-path: /admin
    client:
      enabled: false
  jackson:
    serialization:
    indent_output: true
  application:
    name: iposcloudadmin
server:
  port: 8090
endpoints:
  health:
  sensitive: false
logging:
  level:
   root: info
#eureka:
#  instance:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:admin@localhost:8761/eureka/
