spring:
  application:
    name: iposcloudgate
  cloud:
    config:
      discovery:
       enabled: true
       serviceId: iposcloudregistry
server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@iposcloudregistry:8761/eureka/， http://admin:admin@iposcloudregistry:876/eureka/

# 设置默认超时时间60s（default为全局；若设置某项服务的超时时间，只需要将default替换为对应的服务名）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
